@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

package "Master Data" as master_domain #DDD {

    entity "TB_R_CURRENCY" as currency {
        currency_code : char(3) <<PK>>
        --
        name : varchar(25) NOT NULL
        country_code : char(4) NOT NULL <<FK>>
    }

    entity "TB_R_EXCHANGE_RATE" as exc_rate { 
        exc_rate_code : char(18) <<PK>>
        --
        start_periode : timestamp
        end_periode : timestamp
        currency_code_source : char(3) <<FK>>
        currency_code_target : char(3) <<FK>>
        rate : numeric(15,2)
    }

    exc_rate ||--|{ currency

    entity "TB_M_COUNTRY" as country {
        country_code : char(3) <<PK>>
        --
        country_name : varchar(100) NOT NULL
    }

    entity "ReportingPeriod" as rp {
        reporting_periode_code : char(6) <<PK>>
        --
    }

    entity "TB_M_PARAM" as mp {
        ppr_code : varchar(6) <<PK>> <<FK>>
        --
        param_name : varchar(50) NOT NULL
        param_type : smallint NOT NULL <<ENUM: 0:manhour|1:inland|3:labor>>
        value : numeric(15,2) NOT NULL
    }

    'package SupplierDomain #DDD {
    entity "TB_M_SUPPLIER" as supplier {
        supplier_cd : char(6) <<PK>>
        --
        supplier_nm : varchar(255) NOT NULL
        supplier_address : varchar(255) NULLABLE
    }

    entity "TB_M_PLANT" as plant {
        plant_code : varchar(10) <<PK>>
        --
        supplier_cd : char(6) <<FK>>
        --
    }

    entity "TB_M_DOCK" as dock {
        dock_code : varchar(10) <<PK>>
        --
        supplier_cd : char(6) <<FK>>
    }
    
    rp ||--o{ mp : has many

}

package "TB_R_PACKING_SPEC" as ps_domain #DDD {

    package master #FFF {
      entity "TB_M_MODELS" as model {
        model_cd : char(23) <<PK>>
        --
        model_cfc: char(6)
        model_nm : varchar(100) NULLABLE
        model_remark : varchar(255) NULLABLE
        dest_code : char(4) NOT NULL <<FK>>
        model_impl_period : varchar(6) NOT NULL <<PK>>
        model_type :char(3) NOT NULL <<ENUM: 0:pxp|1:lot|2:eng>>
        project_cd : char(6) NOT NULL <<FK>>
      }

      entity "TB_M_PART" as part {
          part_no : varchar(10) <<PK>>
          --
          part_unique_no : varchar(5) NULLABLE
          suffix_cd : varchar(2) NOT NULL <<FK>>
          part_nm : varchar(255) NOT NULL
          parent_part_no : varchar(10) NULLABLE <<FK>>
          supplier_cd : varchar(10) NULLABLE <<FK>>
          part_dim_length : int
          part_dim_width : int
          part_dim_height : int
          part_weight_per_pc : int
          part_qty_per_box : int
          total_weight : int
      }

      entity "TB_M_DESTINATION" as dest {
          destination_code : varchar(2) <<PK>>
          --
          country_code : char(3) NOT NULL <<FK>>
          destination_country_code : char(4) NULLABLE
          destination_country_name : varchar(100) NULLABLE
      }

      entity "TB_M_PROJECTS" as project {
          project_cd : char(6) <<PK>>
          --
          project_nm : varchar(64) NULLABLE
          project_desc : varchar(256) NULLABLE
          project_mgr : varchar(10) NULLABLE <<FK>>
          project_sts : tinyint NOT NULL <<DEFAULT 1>>
          project_note : varchar(1000) NULLABLE
      }

      note bottom of project
        status: 0:Draft, 1:Active, 
          2:OnHold, 3:Completed
      end note       

      entity "TB_R_MODEL_PARTS" as model_part {
          model_cd : char(23) <<FK>>
          part_no : varchar(10) <<FK>>
          suffix_cd : varchar(2) <<FK>>
          qty : int NOT NULL <<DEFAULT 1>>
      }
      
      model ||--o{ model_part
      part  ||--o{ model_part
      model ||--o| dest : will be sent to
    }

    entity "PreparationTime" as prep_time  #e9dc23ff{
        part_no : varchar(10) <<PK>> <<FK>>
        --
        boxing : int
        stacking : int
    }

    note bottom of prep_time 
      Check this again
    end note 

    entity "TB_M_SUFFIX " as suffix {
        suffix_code : varchar(2) <<PK>>
        --
        note : varchar(10)
    }

    package PackingMaterial #FFF {
      entity "T_R_PACKING_MATERIAL_PRICE" as material_price {
          pmp_code : varchar(12) <<PK>>
          --
          ppr_code : char(6) NOT NULL <<FK>>
          pmp_no : varchar(28) NOT NULL <<FK>>
          pmp_price : numeric(15,2) NOT NULL
      }

      entity "TB_M_MATERIAL" as material {
          material_no : varchar(12) <<PK>>
          --
          supplier_cd : varchar(5) NULLABLE <<FK>>
          material_type : tinyint <<ENUM: Module|Box|Inner|Outer>>
          material_dim_width : numeric(5,2) NOT NULL
          material_dim_height : numeric(5,2) NOT NULL
          material_dim_length : numeric(5,2) NOT NULL
          material_dim_inner_width : numeric(5,2) NOT NULL
          material_dim_inner_length : numeric(5,2) NOT NULL
          material_dim_inner_height : numeric(5,2) NOT NULL
          material_dim_outer_width : numeric(5,2) NOT NULL
          material_dim_outer_length : numeric(5,2) NOT NULL
          material_dim_outer_height : numeric(5,2) NOT NULL
          material_ewh_item_no : varchar(6) NULLABLE <<FK>>
          material_ewh_price : numeric(15,2) NULLABLE
          material_price : numeric(15,2) NOT NULL <<DEFAULT 0.00>>
          currency_cd : char(3) NOT NULL <<FK>> <<DEFAULT 'IDR'>>
          material_mdsds_doc : varchar(255) NULLABLE
          material_drawing_doc : varchar(255) NULLABLE
      }
        
    }

    package Calculation #FFF {
      
      entity "TB_R_CALCULATION" as calc {
        calc_code : varchar(50) <<PK>>
        --
        model_cd : varchar(23) NULLABLE
        impl_period : varchar(6) NULLABLE
        calc_sts : boolean NOT NULL
        calc_date : timestamp NOT NULL
      } 

      note bottom of calc
        status: 0: obsolete 1:up-to-date
      end note

      entity "TB_R_CALCULATION_DETAIL" as calc_dtl {
        calc_dtl_id : int <<PK>> <<AUTO_INCREMENT>>
        --
        calc_code : varchar(50) <<FK>>
        part_no : varchar(28) <<FK>>
      }

      entity "TB_R_CALCULATION_PACKING_DETAIL" as calc_pack_dtl {
        calc_dtl_id : int <<FK>> <<AUTO_INCREMENT>>
        part_no : varchar(28) <<FK>>
        packing_material_price_code : varchar(12) <<FK>>
        /'TBC inland'/
        /'TBC labor'/
      }

      entity "CalculationPart" as calc_part {
        part_no : varchar(28) <<PK>> <<FK>>
        --
        implementation_period : varchar(6), NOT NULL
        inner_cost :numeric (15,2) NULL
        outer_cost :numeric (15,2) NULL
        labor_cost : numeric (15,2) NULL
        inland_cost : numeric (15,2) NULL
      }

      calc ||--|{ calc_dtl
      calc_dtl ||--|{ calc_pack_dtl

    }

    package CPS as cps_domain #FFF {
      
      entity "TB_R_CPS" as packing_spec {
          cps_code : varchar(34)
          --
          cps_code_ref : varchar(28) NULLABLE <<FK>>
          model_code : varchar(6) NOT NULL <<FK>>
          part_no : varchar(12) NOT NULL
          is_active : boolean NOT NULL <<DEFAULT true>>
          cps_type : tinyint NOT NULL <<DEFAULT 0>>
          revision : tinyint NOT NULL <<DEFAULT 0>>
      }

      entity "TB_H_ALL" as hist {
        timestamp : timestamp NOT NULL
        tbl_name : varchar(50) NOT NULL
        field_name : varchar(50) NOT NULL
        action : varchar(10) NOT NULL
        old_value : varchar(255) NULLABLE
        new_value : varchar(255) NULLABLE
        user: varchar(10) NULLABLE
      }

      note top of packing_spec
          composite cps_code = 
            cps_type : 0:CPS, 1:ECI, 2:PSI
            cps_code generated from : dest,
            model, part_no, reporting_period
      end note

      entity "TB_R_CPS_DETAIL" as packing_spec_dtl {
          cps_code : varchar(28) <<FK>>
          --
          packing_material_price_code : varchar(12) <<FK>>
          qty : numeric(5,2) NOT NULL <<DEFAULT 1>>
      }

      entity "TB_R_CPS_PSE_DETAIL" as packing_spec_pse_dtl {
          cps_code : varchar(28) NOT NULL <<FK>>
          --
          packing_plant_current : varchar(6) NULLABLE
          packing_plant_next : varchar(6) NULLABLE
          vanning_plant_current : varchar(6) NULLABLE
          vanning_plant_next : varchar(6) NULLABLE
          category : tinyint NULLABLE 
          importer_line_process : tinyint NULLABLE
          case_code : varchar(4) NULLABLE
          box_number : varchar(1000) NULLABLE
          renban : char(2) NULLABLE
          packing_line : varchar(4) NULLABLE
          packing_process_boxing : tinyint NULLABLE
          packing_process_stacking : tinyint NULLABLE
      }

       note bottom of packing_spec_pse_dtl
        category and packing line :
          0:trim 1:welding 2:hardware, 3:finish
        packing_process_boxing and packing_process_stacking :
          1:TMMIN, 2:supplier
      end note

      entity "TB_R_CPS_LOGISTIC_DETAIL" as packing_spec_logistic_dtl {
          cps_code : varchar(28) <<PK>> <<FK>>
          --
          dock_code :varchar(20) NULLABLE <<FK>>
          remark :varchar(1000) NULLABLE <<FK>>
          process_type : char(2) NULLABLE
          address_rack : varchar (20) NULLABLE
      }

      entity "TB_R_CPS_SUPPLIER_DETAIL" as packing_spec_supplier_dtl {
        cps_code : varchar(28) NULL <<PK>> <<FK>>
        --
        part_weight : numeric (5,2) NULL 
        packing_weight : numeric (5,2) NULL 
        packing_qty : tinyint NULL 
        pcs_kanban : tinyint NULL 
      }

      entity "TB_R_CPS_IMAGE" as cps_image {
        cps_image_id : int <<PK>> <<AUTO_INCREMENT>>
        --
        cps_code : varchar(28) NOT NULL <<FK>>
        cps_image_type : tinyint NOT NULL 
        cps_image_path : varchar(1000) NOT NULL
      }

      entity "TB_R_CPS_REVISION" as cps_rev {
        cps_code : varchar(28) <<PK>> <<FK>>
        --
        revision : tinyint NOT NULL <<DEFAULT 1>>
        changes : text NULLABLE
      }
    
      note top of cps_image
        cps_image_type : 
          0:part, 1:qkp, 2:bkp, 3:outer, 4:inner
      end note

    }
    packing_spec ||-o| packing_spec_supplier_dtl
    packing_spec ||-o| packing_spec_pse_dtl : has pse info detailed
    packing_spec ||-o{ cps_image : has many
    packing_spec ||-o{ packing_spec_dtl : has many
    packing_spec_dtl }|-o| material_price
    packing_spec ||--o| packing_spec_logistic_dtl : has logistic info detailed
    material ||--|{ currency : purchased in

    material ||-o{ material_price : price movement detailed in
}

package Other as other_domain #f5f5f5ff {
  package DocumentDomain #DDD {
      entity "TB_R_DOCUMENT" as doc {
          document_id : varchar <<PK>>
          --
          document_type : tinyint NOT NULL
          document_path : varchar(1000) NOT NULL
      }
  }

  package ApprovalDomain #DDD {
      entity "TB_R_APPROVAL_REQUEST" as request {
          id : char(36) <<PK>> <<UUID>>
          --
          target_type : varchar(50) NOT NULL
          target_id : char(36) NOT NULL <<UUID>>
          status : tinyint NOT NULL 
          created_at : datetime NOT NULL
      }

      note top of request
        status: 0:pending, 1:approved, 2:rejected
      end note

      entity "ApprovalStep" as step {
          id : char(36) <<PK>> <<UUID>>
          --
          request_id : char(36) NOT NULL <<FK>>
          sequence : int NOT NULL
          role_required : varchar(50) NOT NULL
          status : tinyint NOT NULL
      }

      entity "TB_R_APPROVAL_ACTION" as action {
          id : char(36) <<PK>> <<UUID>>
          --
          step_id : char(36) NOT NULL <<FK>>
          user_id : varchar(10) NOT NULL <<FK>>
          action : tinyint NOT NULL <<ENUM: 0:approve|1:reject>>
          comment : text NULLABLE
          action_date : datetime NOT NULL
      }

      request ||--o{ step : has
      step ||--o{ action : has
      request ||--o{ step : has many
      request }|--|| packing_spec : "require approval from \n(target_id = cps_code)"
  }

  package MessagingDomain #DDD {
      entity "TB_R_NOTIFICATION" as notif {
          notification_id : int <<PK>> <<AUTO_INCREMENT>>
          --
          user_code : varchar(10) NOT NULL <<FK>>
          title : varchar(255) NOT NULL
          message : text NOT NULL
          is_read : boolean NOT NULL <<DEFAULT false>>
          created_at : datetime NOT NULL
      }
  }
  package UserManagementDomain #DDD {
      entity "TB_M_USER" as user {
          user_code : varchar(10) <<PK>>
          --
          name : varchar(255) NOT NULL
          role_code : varchar(5) NOT NULL <<FK>>
      }

      entity "TB_M_DEPARTMENT" as dept {
          dept_code : varchar(5) <<PK>>
          --
          name : varchar(100) NOT NULL
          parent_dept_code : varchar(5) NOT NULL <<FK>>
      }

      dept::parent_dept_code --> dept::dept_code

      entity "TB_M_ROLE" as role {
          role_code : varchar(5) <<PK>>
          --
          name : varchar(100) NOT NULL
      }

      entity "TB_M_DEPARTMENT_ROLE" as dept_role {
          dept_code : varchar(5) <<PK>> <<FK>>
          role_code : varchar(5) <<PK>> <<FK>>
          --
      }

      user ||--|| dept : "belong to"
      user }o--|| role : "is a"
      user ||--o{ notif : "receive"
      user ||--o{ action : performs
      project }o--|| user : "managed"
      request }o--|| user : "requested by"
      supplier ||--o{ user : "logged in as "
      dept_role }o--o{ role : "has many"
      dept_role }o--o{ dept : "has many"    
  }
}

' Relationships

part ||--o{ part : "has subparts"
part ||--|{ suffix : has
part ||--o{ prep_time : "prepared within"

supplier ||--o{ part : "produced by"
supplier ||--|{ plant : "has"
supplier ||--|{ dock : "has"

model ||--o{ part : "consists of"
model ||--o{ project : "used in"
model ||--o{ country : "exported to"

project }o--|| dept : "belongs to"

@enduml

/'
====================
SAMPLE RECORDS
====================
### Project

| project_code |
| ------------ |
| IMV          |

---

### Model

| model_code | dest_code | country_code | impl_period | project_code |
| ---------- | --------- | ------------ | ----------- | ------------ |
| 481D       | 722C      | TMT          | 03.2025     | IMV          |
| 481D       | 301B      | TASA         | 05.2025     | IMV          |
| 481D       | 537B      | TSM          | 04.2025     | IMV          |
| 694W       | 709B      | TKM          | 04.2025     | IMV          |

---

### Part

| part_no      | part_name              |
| ------------ | ---------------------- |
| 90430T002300 | GASKET                 |
| 89467BZ02000 | SENSOR, AIR FUEL RATIO |
| 90466T006200 | CLIP, HOSE             |

---

### ModelPart (Model's parts)

| model_code | part_no      | qty |
| ---------- | ------------ | --- |
| 481D       | 90430T002300 | 3   |
| 481D       | 89467BZ02000 | 1   |
| 481D       | 90466T006200 | 1   |

---

### PackingMaterial

| material_no  | material_name |
| ------------ | ------------- |
| B021-227514  | 3I-A          |
| B021-471106  | 3A-A          |
| B021-227514  | 3I-A          |

---

### PackingMaterialPrice

| pmp_code              | material_no  | reporting_period | price |
| --------------------- | ------------ | ---------------- | ----- |
| B021-227514 02 2024   | B021-227514  | 02.2024          | 120   |
| B021-227514 08 2024   | B021-227514  | 08.2024          | 125   |
| B021-471106 02 2024   | B021-471106  | 02.2024          | 240   |
| B021-471106 08 2024   | B021-471106  | 08.2024          | 240   |
| B021-227514 02 2024   | B021-227514  | 02.2024          | 360   |
| B021-227514 08 2024   | B021-227514  | 08.2024          | 366   |

---

### PackingSpec

| cps_code                | model_code | is_active | revision |
| ----------------------- | ---------- | --------- | -------- |
| 722C 481D 90430T002300  | 481D       | TRUE      | 3        |
| 722C 024J 90430T002300  | 024J       | TRUE      | 1        |

---

### PackingSpecDtl

| cps_code                | pmp_id                | qty |
| ----------------------- | --------------------- | --- |
| 722C 481D 90430T002300  | B021-227514 02 2024   | 1   |
| 722C 024J 90430T002300  | B021-471106 02 2024   | 2   |

---

### PackingSpecRevision

| cps_code                | revision | changes                                                              |
| ----------------------- | -------- | -------------------------------------------------------------------- |
| 722C 481D 90430T002300  | 2        | `{' pmp_id: B021-227514 02 2024 , action: insert, qty: 1 }`         |

---

### Calculation

| calc_code         | status     |
| ----------------- | ---------- |
| 2024 08 TAR TEST  | up-to-date |

---

### CalcDetail

| calc_code         | cps_code                |
| ----------------- | ----------------------- |
| 2024 08 TAR TEST  | 722C 481D 90430T002300  |
| 2024 08 TAR TEST  | 722C 024J 90430T002300  |

---

### CalcCost

| calc_code         | cps_code                | reporting_period | inner_cost | outer_cost | labor_cost | inland_cost |
| ----------------- | ----------------------- | ---------------- | ---------- | ---------- | ---------- | ----------- |
| 2024 08 TAR TEST  | 722C 481D 90430T002300  |                  |            |            |            |             |
| 2024 08 TAR TEST  | 722C 024J 90430T002300  |                  |            |            |            |             |

---

### History

| id | timestamp        | tbl_name       | action | field_name | old_value               | new_value               | user |
| -- | ---------------- | -------------- | ------ | ---------- | ----------------------- | ----------------------- | ---- |
|    | 02.03.2025 09:10 | PackingSpec    | update | cps_code   | 722C 481D 90430T002300  | 722C 481D 90430T002301  | ari  |
|    | 02.03.2025 09:15 | PackingSpecDtl | insert | cps_code   | NULL                    | 722C 481D 90430T002300  | ari  |


====================================================
SAMPLE Records to illustrate Approval process works
====================================================

ApprovalRequest
| id (UUID) | target\_type  | target\_id (UUID) | status     | created\_at         |
| --------- | ------------- | ----------------- | ---------- | ------------------- |
| `req-001` | `PackingSpec` | `ps-789`          | `Approved` | 2025-07-17 09:00:00 |


ApprovalSteps
| id       | request\_id | sequence | role\_required | status   |
| -------- | ----------- | -------- | -------------- | -------- |
| step-001 | req-001     | 1        | `PIC`          | Approved |
| step-002 | req-001     | 2        | `Section Head` | Approved |
| step-003 | req-001     | 3        | `Dept Head`    | Approved |

ApprovalActions
| id      | step\_id | user\_id | action  | comment            | action\_date        |
| ------- | -------- | -------- | ------- | ------------------ | ------------------- |
| act-101 | step-001 | user-01  | Approve | "Looks good."      | 2025-07-17 09:05:00 |
| act-102 | step-002 | user-02  | Approve | "Reviewed and OK." | 2025-07-17 10:00:00 |
| act-103 | step-003 | user-03  | Approve | "Final approval."  | 2025-07-17 11:00:00 |

User
| id      | name    | role         |
| ------- | ------- | ------------ |
| user-01 | Alice   | PIC          |
| user-02 | Boby     | Section Head |
| user-03 | Charlie | Dept Head    |

'/