@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho


package "Master Data" {
  '### master_params
  entity "TB_M_ASSUMPTION" as params {
    period varchar(6) not null (PK)
    --
    ppr_month_start varchar(2) not null
    ppr_month_end varchar(2) not null
    inflation_labor_percentage numeric(3,2)
    inflation_FOH_var_percentage numeric(3,2)
    inflation_FOH_fix_percentage numeric(3,2)
    inflation_incremental_depreciation_percentage numeric(3,2) 
    cr_labor_percentage numeric(3,2)
    cr_FOH_var_percentage numeric(3,2)
    cr_FOH_fix_percentage numeric(3,2)
    cr_incremental_depreciation numeric(3,2)
    threshold_lower_limit_percentage numeric(3,2)
    threshold_upper_limit_percentage numeric(3,2)
  }

  entity "TB_M_VOLUME_ASSUMPTION" as master_eg_model {
    period varchar (6) not null (FK, PK)
    eg_model varchar(6) not null (PK)
    --
    total_volume numeric(15,2) null
    export_only  numeric(15,2) null
    for_vh  numeric(15,2) null
  }

  params ||--|| master_eg_model : has many

  entity "TB_M_EG_MODEL" as eg_model {
    part_no varchar(12) not null (FK, PK)
    importer varchar(3) not null (FK)
    eg_model varchar(6) not null (FK)
    eg_type varchar(6) not null (FK)
  }

  '### PARTS
  entity "TB_M_PPR_EXPORT_PBMD" as parts {
    part_no varchar(12) not null (PK)
    --
    importer varchar(3) not null 
    eg_type varchar(6) not null
    eg_model varchar(6) not null
  }

  '### COST ITEM MASTER
  entity "TB_M_COST_ITEMS" as ci_master {
    category_id varchar(4) not null (PK)
    --
    category_name varchar(25) not null
  }    

  '### COST ITEM MAPPING
  entity "TB_M_COST_ITEMS_MAPPING" as ci_dtl
  {
    ci_dtl_id not null (PK) 
    ---
    parent_category_id varchar(4) not null (FK)
    ci_dtl_category_name varchar(50) not null
  }
  
  ci_master |o-{ ci_dtl


  '### RATIO IMPACT PER CATEGORY
  'for material costs ratio impact per material category column lookup column
  'source : material cost report
  entity "TB_R_RATIO_IMPACT_PER_CATEGORY" as ripc {
    period varchar(7) not null (PK)
    material_category varchar(50) not null (PK)
    --
    ratio_impact numeric(15,2) not null
  }  

  entity "TB_M_RAW_MATERIAL" as raw_material {
    material_no varchar(12) not null (PK)
    --
    material_name varchar(100) not null 
    material_category varchar(50) not null
    cost_center varchar(7) not null
  }

}


package "INPUT SOURCES" as source {
  '### PROCESS COST
  'for cost items process cost calculation 
  entity "TB_T_PROCESS_COST" as process_cost {
    period varchar(7) not null (FK, PK)    /'ppr period'/
    plant varchar(5) not null (FK, PK)
    material_number varchar(12) not null (FK, PK)
    "header" varchar(24) not null (FK, PK)           /'category_name'/
    main_cost_component_name varchar(50) (FK, PK)    /'ci_dtl_category_name'/
    --
    quantity numeric(7,2)  not null
    total_value numeric(15,2) not null
    status_code   tinyint     not null
    status_message varchar(255)
  
  }

  '### PROCESS COST SUMMARY
  'Summary of Process Cost per material category
  entity "TB_R_PROCESS_COST_SUMMARY" as process_cost_summary {
    period_year varchar(7) not null (FK, PK) 
    material_number varchar(12) not null (FK, PK)
    "header" varchar(24) not null (FK, PK)   /' value: Labor, FOH Var, FOH Fix, Exclusive Investment, etc, taken from Header column in Process Cost table'/
    --
    quantity numeric(7,2)  not null
    total_value numeric(15,2) not null
  }

  process_cost_summary ||--|{ process_cost : detailed in

  '### TOOLING OH
  'for cost items tooling outhouse cost calculation
  entity "TB_T_TOOLING" as toolingTemplate {
    period varchar(6) not null (FK)
    eg_model varchar(6) not null (PK)
    --
    total_price_per_unit(15,2)not null
    status_code   tinyint     not null
    status_message varchar(255)
   }

  entity "TB_R_TOOLING_OH" as tooling_OH {
    period varchar(6) not null (FK)
    eng_model varchar(6) not null (PK)
    --
    total_price_per_unit numeric(15,2) not null
  }  

  

   toolingTemplate ||--|| tooling_OH  : based on

  entity "TB_T_PRODUCT_VOLUME" as prodUpload {
    period varchar(6) not null (FK) (PK)
    material varchar (50) not null (FK) (PK) /'material no'/
    --
    base_quantity numeric(7,2) not null
    status_code   tinyint     not null
    status_message varchar(255)
  }
  entity "TB_R_PRODUCT_VOLUME" as prod_vol {
    period varchar(6) not null (FK) (PK)
    material varchar (50) not null (FK) (PK) /'material no'/
    --
    base_quantity numeric(7,2) not null
  }

  prodUpload ||--|| prod_vol : processed to

  
  entity "TB_T_SALES_VOLUME" as salesUpload {
    period varchar(6) not null (PK, FK)
    product varchar(24) not null (PK, FK)  /'part_no'/
    --
    eng_model varchar(6) not null
    eng_type varchar(6) not null
    quantity numeric(7,2) not null
    uom varchar(4) not null
    status_code   tinyint     not null
    status_message varchar(255)
  }

  entity "TB_R_SALES_VOLUME" as sales_vol {
    period varchar(6) not null (PK, FK)
    product varchar(24) not null (PK, FK)  /'part_no'/
    --
    eng_model varchar(6) not null
    eng_type varchar(6) not null
    quantity numeric(7,2) not null
    uom varchar(4) not null
  }


  salesUpload ||--|| sales_vol : processed to

  parts ||-o{ sales_vol : sold

  entity "TB_T_GPQ" as gpq {
    period varchar(6) not null (PK)
    cost_center varchar(7) not null (PK)
    --
    tr_nr varchar(1) not null
    gpq numeric(15,2 ) not null
    status_code   tinyint  not null
    status_message varchar(255)
  }


  ' entity "TB_R_GPQ" as gpq_summary {
  '   period varchar(6) not null (PK)
  '   cost_center varchar(7) not null (PK)
  '   tr_nr varchar(1) not null (PK)
  '   gpq numeric(15,2 ) not null
  ' }

  ' gpq_summary ||--|| gpq : summarized from
  
  '### COST CENTER
  entity "TB_T_COST_CENTER" as cc {    
    part_no varchar(12) not null (PK, FK)
    cost_center varchar(7) not null (PK, FK)
    period varchar(6) not null (PK, FK)  /'ppr period'/
    --
    status_code   tinyint     not null
    status_message varchar(255)
  }

  parts }|--|{ cc : belongs to

  entity "TB_R_GPQ_CC" as cc_summary {
    part_no     varchar(12) not null (FK, PK)
    cost_center varchar(7) not null (FK, PK)
    period varchar(6) not null (PK, FK)
    key varchar(14) not null (PK)
    gpq numeric(15,2 ) not null
  } 
  
  cc_summary ||--|| cc : summarized from
  cc_summary ||--|| gpq : fetch gpq value from

  'entity "TB_R_RATIO_AND_GENTANI_IMPACT" as ragi {
  entity "TB_T_CASTING_MATERIAL" as ragi {
    period varchar(6) not null (PK)
    eg_model varchar(6) not null (PK)
    eg_type varchar(6) not null (PK)
    cost_center varchar(7) not null (PK)
    material_no varchar(12) not null (PK)
    material_name varchar(100) not null (PK)
    material_category varchar(50) not null (PK)
    --
    price numeric(15,2) not null
    gentani numeric(15,2) not null
    total numeric(15,2) not null
    status_code   tinyint     not null
    status_message varchar(255)
  }

  raw_material ||--|{ ragi : belongs to
  ragi }|--|| eg_model : importer is

}

package "REPORT" {
  '### MATERIAL COST
  'for cost items material cost calculation
  entity "TB_R_MATERIAL_COST_REPORT" as mat_cost_rpt {
    period varchar(6) not null (PK)
    eg_model varchar(6) not null (FK, PK)
    eg_type varchar(6) not null (FK, PK)
    casting_part varchar(50) (PK)
    cc varchar(7) not null (FK, PK) 
    material_no varchar(12) not null (PK)
    --
    material_name varchar(100)
    material_category varchar(50)
    
    price_current numeric(15,2) not null
    gentani_current numeric(15,2) not null
    total_current numeric(15,2) not null
    
    price_prev numeric(15,2) not null
    gentani_prev numeric(15,2) not null
    total_prev numeric(15,2) not null
    
    diff_amt numeric(15,2) not null
    diff_percentage numeric(15,2) not null
    analysis_price_impact numeric(15,2)
    analysis_ratio_impact numeric(15,2)
    analysis_gentani_impact numeric(15,2)
    
    remark_price_impact varchar(100)
    remark_ratio_gentani_impact varchar(100)
  }

  '### IHP COST
  entity "TB_R_IHP_COST" as ihp {
    part_no varchar(12) not null (FK, PK)
    importer varchar(3) not null (PK)
    eg_type varchar(6) not null (PK)
    eg_model varchar(6) not null (PK)
    period varchar(6) not null (FK, PK)
    --
    tooling_oh_current numeric(12,2)
    raw_material_current numeric(12,2)
    TOTAL_purchase_cost_current numeric(12,2)
    labor_current numeric(12,2)
    foh_fix_current numeric(12,2)
    foh_var_current numeric(12,2)
    depre_common_current numeric(12,2)
    depre_exclusive_current numeric(12,2)
    TOTAL_process_cost_current numeric(12,2)
    manhour_current numeric(12,2)
    sales_volume_current numeric(12,2)
    prod_volume_current numeric(12,2)

    tooling_oh_prev numeric(12,2)
    raw_material_prev numeric(12,2)
    TOTAL_purchase_cost_prev numeric(12,2)
    labor_prev numeric(12,2)
    foh_fix_prev numeric(12,2)
    foh_var_prev numeric(12,2)
    depre_common_prev numeric(12,2)
    depre_exclusive_prev numeric(12,2)
    TOTAL_process_cost_prev numeric(12,2)
    manhour_prev numeric(12,2)
    sales_volume_prev numeric(12,2)
    prod_volum_preve numeric(12,2)

    tooling_oh_pbmd numeric(12,2)
    raw_material_pbmd numeric(12,2)
    TOTAL_purchase_cost_pbmd numeric(12,2)
    labor_pbmd numeric(12,2)
    foh_fix_pbmd numeric(12,2)
    foh_var_pbmd numeric(12,2)
    depre_common_pbmd numeric(12,2)
    depre_exclusive_pbmd numeric(12,2)
    TOTAL_process_cost_pbmd numeric(12,2)
    manhour_pbmd numeric(12,2)
    sales_volume_pbmd numeric(12,2)
    prod_volum_prevpbmdmeric(12,2)    
  }

  ihp ||--o| params : calculated using
  ihp ||--|| tooling_OH : has tooling OH dtl of
  ihp ||--|| mat_cost_rpt : has material cost dtl of
  ihp ||--|| prod_vol : has detail product volume of  
  ihp ||--|| process_cost_summary : has process cost dtl of
  ihp ||--|| ragi : has ratio and gentani impact dtl of

'### IHP ANLYSIS
entity "TB_R_IHP_ANALYSIS" as analysis {
  part_no varchar(12) not null (FK, PK)
  importer varchar(3) not null (PK)
  eg_type varchar(6) not null (PK)
  eg_model varchar(6) not null (PK)
  period varchar(6) not null (FK, PK)
  --
  tooling_oh_volume numeric(12,2)
  raw_material_volume numeric(12,2)
  TOTAL_purchase_cos_volume numeric(12,2)
  labo_volume numeric(12,2)
  foh_fi_volume numeric(12,2)
  foh_va_volume numeric(12,2)
  depre_common_volume numeric(12,2)
  depre_exclusiv_volume numeric(12,2)
  TOTAL_process_cost_volume numeric(12,2)
  manhour_volume numeric(12,2)
  sales_volume_volume numeric(12,2)
  prod_volume_volume numeric(12,2)
  
  tooling_oh_inflation numeric(12,2)
  raw_material_inflation numeric(12,2)
  TOTAL_purchase_cost_inflation numeric(12,2)
  labo_inflation numeric(12,2)
  foh_fi_inflation numeric(12,2)
  foh_va_inflation numeric(12,2)
  depre_common_inflation numeric(12,2)
  depre_exclusiv_inflation numeric(12,2)
  TOTAL_process_cos_inflation numeric(12,2)
  manhour_inflation numeric(12,2)
  sales_volum_inflation numeric(12,2)
  prod_vol_inflationme numeric(12,2)

  tooling_oh_cr numeric(12,2)
  raw_materia_cr numeric(12,2)
  TOTAL_purchase_cost_cr numeric(12,2)
  labor_cr numeric(12,2)
  foh_fi_cr numeric(12,2)
  foh_var_cr numeric(12,2)
  depre_common_cr numeric(12,2)
  depre_exclusive_cr numeric(12,2)
  TOTAL_process_cost_cr numeric(12,2)
  manhou_cr numeric(12,2)
  sales_volume_cr numeric(12,2)
  prod_volume_cr numeric(12,2)

  tooling_oh_material_price_impact numeric(12,2)
  raw_material_material_price_impact numeric(12,2)
  TOTAL_purchase_cost_material_price_impact numeric(12,2)
  labor_material_price_impact numeric(12,2)
  foh_fix_material_price_impact numeric(12,2)
  foh_var_material_price_impact numeric(12,2)
  depre_common_material_price_impact numeric(12,2)
  depre_exclusive_material_price_impact numeric(12,2)
  TOTAL_process_cost_material_price_impact numeric(12,2)
  manhour_material_price_impact numeric(12,2)
  sales_volume_material_price_impact numeric(12,2)
  prod_volume_material_price_impact numeric(12,2)

  tooling_oh_material_ratio_impact numeric(12,2)
  raw_material_material_ratio_impact numeric(12,2)
  TOTAL_purchase_cost_material_ratio_impact numeric(12,2)
  labor_material_ratio_impact numeric(12,2)
  foh_fix_material_ratio_impact numeric(12,2)
  foh_var_material_ratio_impact numeric(12,2)
  depre_common_material_ratio_impact numeric(12,2)
  depre_exclusive_material_ratio_impact numeric(12,2)
  TOTAL_process_cost_material_ratio_impact numeric(12,2)
  manhour_material_ratio_impact numeric(12,2)
  sales_volume_material_ratio_impact numeric(12,2)
  prod_volume_material_ratio_impact numeric(12,2)

  tooling_oh_others numeric(12,2)
  raw_material_others numeric(12,2)
  TOTAL_purchase_cost_others numeric(12,2)
  labor_others numeric(12,2)
  foh_fix_others numeric(12,2)
  foh_var_others numeric(12,2)
  depre_common_others numeric(12,2)
  depre_exclusive_others numeric(12,2)
  TOTAL_process_cost_others numeric(12,2)
  manhour_others numeric(12,2)
  sales_volume_others numeric(12,2)
  prod_volume_others numeric(12,2)  
}  

ihp ||--|| analysis

  ' period_year varchar(7) not null
  ' plant varchar(5) not null
  ' material_number varchar(12) not null
  ' header varchar(24) not null
  ' main_cost_component_name varchar(50) not null
  ' quantity numeric(7,2) not null


}


@enduml

/' SAMPLE DATA

===================
  MASTER TABLES
-------------------
---
### PARTS
source : from PBMD DB

| part_no       | importer | eg_type | eg_mnodel |
| ------------- | -------- | -------- | -------- |
| 51401-KWW-641 | TDR      | H2V      | NR       |
| 51402-KWW-640 | TDR      | H2V      | NR       |
| 51402-KWW-641 | TMV      | H2V      | NR       |
| 51402-KWW-643 | TDR      | ICE      | TR       |

---
### MASTER PARAMS

| period | period_start | period_end | inflation_labor_percentage | inflation_foh_fix_percentage | inflation_foh_var_percentage | inflation_incremental_depreciation | cr_labor_percentage | cr_foh_fix_percentage | cr_foh_var_percentage | cr_incremental_depreciation | thereshold_lower_limit_percentage | thereshold_upper_limit_percentage |
| ---------- | ------------ | ---------- | -------------------------- | ---------------------------- | ---------------------------- | ---------------------------------- | ------------------- | --------------------- | --------------------- | --------------------------- | --------------------------------- | ----------------------------------|
| 022025     | 09           | 02         | 3,1                        | 2,1                          | 3,2                          | 3,2                                | 3                   | 2                     | 2,2                   | 2,3                         | 15                                | 15                                |


---
### MASTER EG MODEL ASSUMPTION
| period | eg_model | total_volume | export_only | for_vh   |
| ---------- | -------- | ------------ | ----------- |--------- |
| 022025     | NR       | 16.410 	     | 17.566 	   | 1.156 	  |
| 022025     | TR       | 105.581 	   | 93.945 	   | -11.636  |


---
### COST ITEM MASTER
| category_id | category_name         |
| ----------- | --------------------- |
| CI001       | LABOR                 |
| CI002       | FOH Fixed             |
| CI003       | FOH Var               | 
| CI004       | Exclusive Investment  |


---
### COST ITEM MAPPING
parent_category_id   | child_category_name    |
-------------------- | ---------------------- |
CI001                | Labor A                |
CI001                | Labor B                |
CI001                | Labor C                |
CI001                | Labor D & Others       |
CI001                | Bonus & Retirement A	  |
CI001                | Bns & Rtrmnt D & oth	  |
CI001                | Bonus & Retirement B	  |
CI001                | Bonus & Retirement C	  |
CI001                | Division exp - Labor	  |
CI002                | General expense        |
CI002                | Tax & Insurance        |
CI002                | Repair & Maintenance 	|
CI002                | R&M Forging Mold	      |
CI002                | Division exp - Other	  |
CI002                | Operating supply	      |
CI003                | Consumable tools	      |
CI003                | Utilities	            |
CI003                | Interplant	            |
CI003                | Depr. - Common Unex.	  |
CI003                | Division exp - Depre	  |
Exclusive Investment | Depr. - Unique Unex.	  |



===============================
  INPUT SOURCES and MID TABLES
-------------------------------

---
### PROD VOLUME


| Material   | eBaseQuantity |
| ---------- | ------------- |
| 120000C470 |             9 |
| 120000C580 |            15 |
| 170000C280 |            28 |
| 170000C540 |             3 |
| 120000C560 |             6 |
| 170000C320 |            39 |
| 120000C640 |            20 |
| 170000C490 |            18 |
| 12000BZJ30 |             5 |
| 16000BZU70 |             8 |
| 12000BZJ00 |            17 |
| 16000BZ770 |            13 |
| 160000Y700 |           128 |
| 16000BZV20 |            18 |
| 160000Y680 |            65 |
| 16000BZU80 |            92 |
| 16000BZQ60 |             7 |
| 16000BZW50 |            17 |
| 120000Y340 |             8 |
| 16000BZQ20 |            11 |
| 16000BZV40 |            40 |
| 12000BZE50 |            66 |


---
### SALES VOLUME

| Product    | Eng.Model | Eng.Type | Quantity | Uom |
| ---------- | --------- | -------- | -------: | --- |
| 120000C380 | TR        | 2TR      |       60 | PC  |
| 170000C490 | TR        | 2TR      |       54 | PC  |
| 170000C510 | TR        | 2TR      |       60 | PC  |
| 120000C370 | TR        | 2TR      |       12 | PC  |
| 120000C580 | TR        | 1TR      |      198 | PC  |
| 170000C490 | TR        | 2TR      |      606 | PC  |
| 120000C640 | TR        | 2TR      |      600 | PC  |
| 120000C380 | TR        | 2TR      |        6 | PC  |
| 120000C640 | TR        | 2TR      |      414 | PC  |
| 120000C580 | TR        | 1TR      |      336 | PC  |
| 120000C580 | TR        | 1TR      |      330 | PC  |
| 120000C640 | TR        | 2TR      |      570 | PC  |
| 170000C490 | TR        | 2TR      |      582 | PC  |
| 120000C640 | TR        | 2TR      |      552 | PC  |
| 120000C580 | TR        | 1TR      |      378 | PC  |
| 120000C210 | TR        | 1TR      |       18 | PC  |


---
### TOOLING OH

| ppr_period | Car Series	| TotalPrice/Unit | 
| ---------- | ---------- | --------------- |
| 022025     | TR	        | 539.962.00      |
| 022025     | TR	        | 539.962.00      |
| 022025     | TR	        | 539.962.00      |
| 022025     | TR	        | 539.962.00      |
| 022025     | TR	        | 539.962.00      |
| 022025     | TR	        | 539.962.00      |
| 022025     | IMV4	      | 758.465.00      |
| 022025     | IMV4	      | 758.465.00      |
| 022025     | IMV4	      | 758.465.00      |
| 022025     | IMV4	      | 758.465.00      |
| 022025     | IMV4	      | 758.465.00      |


---
### GPQ
| Period   | Cost Center | TR/NR	| GPQ    |
| -------- | ------------| ------ | ------ |
| 04.2025  | AZP004	     |  TR	  | 2.626  |
| 04.2025  | AQM200	     |  NR	  | 3      |
| 04.2025  | AQM100	     |  NR	  | 1      |
| 04.2025  | AQM300	     |  NR	  | 12.164 |
| 04.2025  | AQM300	     |  NR	  | 5.100  |
| 04.2025  | AQM400	     |  NR	  | 16.517 |
| 04.2025  | AQM400	     |  NR	  | 774    | 
| 04.2025  | AQM400	     |  NR	  | 16.518 |
| 04.2025  | AQM400	     |  NR	  | 776    |
| 04.2025  | AQM200	     |  NR	  | 9.703  |
| -------- | ------------| ------ | ------ |        
| 05.2025	 | AZP004	     |  TR    | 3.011  |
| 05.2025	 | AQM200	     |  NR    | 2      |
| 05.2025	 | AQM200	     |  NR    | 10     |
| 05.2025	 | AQM100	     |  NR    | 19     |
| 05.2025	 | AQM300	     |  NR    | 12.617 |
| 05.2025	 | AQM300	     |  NR    | 5.764  |
| 05.2025	 | AQM400	     |  NR    | 17.602 |
| 05.2025	 | AQM400	     |  NR    | 794    |
| 05.2025	 | AQM400	     |  NR    | 17.605 |
| -------- | ------------| ------ | ------ |


Sum GPQ and Group by Period, CC, TR/NR and inserterd to PV GPQ Table
---
### TB_T_GPQ
### Sheet : PV GPQ
Looked up by CC data using keys : Cost Center + Period
| Period   | Cost Center | TR/NR	| GPQ    |
| -------- | ------------| ------ | ------ |
| 04.2025  | AZP004	     |  TR	  | 2.626  |
| 04.2025  | AQM200	     |  NR	  | 3      |
| 04.2025  | AQM100	     |  NR	  | 1      |
| 04.2025  | AQM300	     |  NR	  | 12.164 |
| 04.2025  | AQM300	     |  NR	  | 5.100  |
| 04.2025  | AQM400	     |  NR	  | 16.517 |
| 04.2025  | AQM400	     |  NR	  | 774    | 
| 04.2025  | AQM400	     |  NR	  | 16.518 |
| 04.2025  | AQM400	     |  NR	  | 776    |
| 04.2025  | AQM200	     |  NR	  | 9.703  |


---
### COST CENTER
| Material Code/Part No | Cost Center | Period  
| --------------------- | ----------- | ------- 
| 51401-KWW-641         | CAST-4350   | 2024-08 
| 51401-KWW-641         | CAST-4350   | 2025-02 
| 51401-KWW-641         | MACH-4350   | 2024-08 
| 51401-KWW-641         | MACH-4350   | 2025-02 
| 51402-KWW-640         | CAST-4350   | 2024-08 
| 51402-KWW-640         | CAST-4350   | 2025-02 
| 51402-KWW-640         | MACH-4350   | 2024-08 
| 51402-KWW-640         | MACH-4350   | 2025-02 
| 51402-KWW-641         | CAST-4350   | 2024-08 
| 51402-KWW-641         | CAST-4350   | 2025-02 
| 51402-KWW-641         | MACH-4350   | 2024-08 
| 51402-KWW-641         | MACH-4350   | 2025-02 
| 51402-KWW-643         | CAST-4350   | 2024-08 
| 51402-KWW-643         | CAST-4350   | 2025-02 
| 51402-KWW-643         | MACH-4350   | 2024-08 
| 51402-KWW-643         | MACH-4350   | 2025-02 


---
### TB_T_CC
### PV Cost Center 
File : GPQ CC EG
Sheet : PV CC
Note:
Key   = CC + Period 
Key 1 = Part No + Period 
Fetch GPQ value from PV GPQ Table using Key

| Material Code/Part No | Cost Center | Period  | Key               | GPQ    | Key 1                 |
| --------------------- | ----------- | ------- | ----------------- | ------ | --------------------- |
| 51401-KWW-641         | CAST-4350   | 2024-08 | CAST-4350_2024-08 | 9850   | 51401-KWW-641_2024-08 |
| 51401-KWW-641         | CAST-4350   | 2025-02 | CAST-4350_2025-02 | 10120  | 51401-KWW-641_2025-02 |
| 51401-KWW-641         | MACH-4350   | 2024-08 | MACH-4350_2024-08 | 9750   | 51401-KWW-641_2024-08 |
| 51401-KWW-641         | MACH-4350   | 2025-02 | MACH-4350_2025-02 | 10050  | 51401-KWW-641_2025-02 |
| 51402-KWW-640         | CAST-4350   | 2024-08 | CAST-4350_2024-08 | 9920   | 51402-KWW-640_2024-08 |
| 51402-KWW-640         | CAST-4350   | 2025-02 | CAST-4350_2025-02 | 10200  | 51402-KWW-640_2025-02 |
| 51402-KWW-640         | MACH-4350   | 2024-08 | MACH-4350_2024-08 | 9850   | 51402-KWW-640_2024-08 |
| 51402-KWW-640         | MACH-4350   | 2025-02 | MACH-4350_2025-02 | 10100  | 51402-KWW-640_2025-02 |
| 51402-KWW-641         | CAST-4350   | 2024-08 | CAST-4350_2024-08 | 8950   | 51402-KWW-641_2024-08 |
| 51402-KWW-641         | CAST-4350   | 2025-02 | CAST-4350_2025-02 | 9200   | 51402-KWW-641_2025-02 |
| 51402-KWW-641         | MACH-4350   | 2024-08 | MACH-4350_2024-08 | 8850   | 51402-KWW-641_2024-08 |
| 51402-KWW-641         | MACH-4350   | 2025-02 | MACH-4350_2025-02 | 9100   | 51402-KWW-641_2025-02 |
| 51402-KWW-643         | CAST-4350   | 2024-08 | CAST-4350_2024-08 | 9450   | 51402-KWW-643_2024-08 |
| 51402-KWW-643         | CAST-4350   | 2025-02 | CAST-4350_2025-02 | 9750   | 51402-KWW-643_2025-02 |
| 51402-KWW-643         | MACH-4350   | 2024-08 | MACH-4350_2024-08 | 9350   | 51402-KWW-643_2024-08 |
| 51402-KWW-643         | MACH-4350   | 2025-02 | MACH-4350_2025-02 | 9650   | 51402-KWW-643_2025-02 |



| Costing Date | period      | Costing Status | Plant | Material Number | Header       | Main Cost Component Name | Quantity |
| ------------ | ----------- | -------------- | ----- | --------------- | ------------ | ----------------------- | --------- |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | Direct(Raw) Material    | 3083.00   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | LSP - Part Cost         | 450.50    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | Milk Run Cost           | 125.75    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | MSP - Part Cost         | 280.25    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | MSP - Freight           | 85.50     |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | MSP - Landing Charge    | 42.75     |  
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Raw Material | MSP - Insurance         | 32.25     |   
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Labor A                 | 1200.50   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Labor B                 | 480.25    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Labor C                 | 560.75    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Labor D & Others        | 724.00    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Bonus & Retirement A    | 305.50    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Bonus & Retirement B    | 240.25    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Bonus & Retirement C    | 330.00    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Labor        | Bns & Rtrmnt D & oth    | 125.00    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Fixed    | General expense         | 1545.50   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Fixed    | Tax & Insurance         | 773.50    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Fixed    | Repair & Maintenance    | 773.00    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Fixed    | R&M Forging Mold        | 225.75    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Fixed    | Division exp - Other    | 407.50    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Variable | Operating supply        | 1585.00   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Variable | Consumable tools        | 1585.00   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Variable | Utilities               | 892.50    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | FOH Variable | Interplant              | 450.75    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Depreciation | Depr. - Common Unex.    | 3358.00   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Depreciation | Depr. - Unique Unex.    | 504.00    |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Depreciation | Division exp - Depre    | 1672.00   |
| 2024-08-01   | 2024-08     | KA             | 4350  | 51401-KWW-641   | Depreciation | Division exp - Labor    | 795.50    |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Raw Material | Direct(Raw) Material    | 3113.00   |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Raw Material | JSP - Part Cost         | 520.75    |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Raw Material | JSP - Freight           | 92.50     |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Raw Material | JSP - Landing Charge    | 38.25     |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Raw Material | JSP - Insurance         | 28.75     |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Labor        | Labor A                 | 1198.25   |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Labor        | Labor B                 | 502.50    |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Labor        | Labor C                 | 475.75    |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Labor        | Bonus & Retirement A    | 318.75    |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | FOH Fixed    | General expense         | 1560.50   |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | FOH Fixed    | Tax & Insurance         | 780.25    |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | FOH Variable | Operating supply        | 1600.00   |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | FOH Variable | Consumable tools        | 1600.00   |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Depreciation | Depr. - Common Unex.    | 3388.00   |
| 2025-02-01   | 2025-02     | KA             | 4350  | 51402-KWW-640   | Depreciation | Depr. - Unique Unex.    | 508.00    |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | Raw Material | Direct(Raw) Material    | 2828.00   |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | Raw Material | LSP - Part Cost         | 385.50    |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | Labor        | Labor A                 | 1236.00   |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | Labor        | Labor B                 | 492.75    |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | FOH Fixed    | General expense         | 1464.50   |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | Depreciation | Depr. - Common Unex.    | 2997.00   |
| 2024-08-15   | 2024-08     | KA             | 4350  | 51402-KWW-641   | Depreciation | Depr. - Unique Unex.    | 450.00    |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | Raw Material | Direct(Raw) Material    | 2669.00   |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | Raw Material | MSP - Part Cost         | 295.75    |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | Labor        | Labor A                 | 1223.50   |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | Labor        | Labor C                 | 428.25    |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | FOH Fixed    | Tax & Insurance         | 792.25    |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | FOH Variable | Utilities               | 755.00    |      
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | Depreciation | Depr. - Common Unex.    | 3149.00   |
| 2025-02-15   | 2025-02     | KA             | 4350  | 51402-KWW-643   | Depreciation | Depr. - Unique Unex.    | 472.00    |


---
# RATIO AND GENTANI IMPACT
| eriod      | eg_model | eg_type | casting_part  | cc      | material_no | material_name                                 | material_category | price | gentani | total |
|----------- | -------- | ------- | ------------- | ------- | ----------- | --------------------------------------------- | ----------------- | ----- | ------- | ----- |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-031560	| CARBON DTCA-09 DURATIGHT / OCTO	              | Additive	        | 1	    |    0,50	| 500	  |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-031561	| CARBURIZER CARBON RISER HCM-A(CPC-A)OCTO	    | Additive	        | 1.25	|    0,20	| 250	  |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-033558	| RECARBURIZER DG-LNS MARUTOYO	                | Additive	        | 1.1	  |    0,30	| 330	  |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-160900	| Scrap ex Import Stamping (inhouse) 99.44%	    | Scrap	            | 2	    |    0,30	| 600	  |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-160900	| STEEL RAW MATERIAL SHEET EX STAMPING	        | Scrap	            | 2	    |    0,20	| 400	  |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-160901	| Scrap ex Karawang (Inhouse) 0.16%	            | Scrap	            | 2	    |    0,20	| 400	  |
| 0420205    |     TR	  |   1TR   |	Block Cylinder| AZC100	| B895-160901	| STEEL RAW MATERIAL IN-HOUSE CASTING (KRW)	    | Scrap	            | 2	    |    0,30	| 600	  |

--
### GENTANI SUM PER CATEGORY 
Source :
Ref : Casting Kalkulasi 1
Note: Middle Table for Casting Material Cost Report creation, to calculate sum of gentani cost per category per period

| period     | material_category | gentani_sum_current | gentani_sum_prev |
| ---------- | ----------------- | ------------------- | ---------------- | 
| 042025     | Additive          | 3000                | 2500             | 
| 042025     | Scrap OH          | 3000                | 2500             | 

--
### COST ITEM PER PERIOD
TB_T_PROCESS_COST_SUMMARY
source: 
File : Act Cost Report
Sheet : 120000C370
Note:
key : resource_name + period_year
GPQ CC column fetch from TB_T_CC using key (part_no/resource_name) + period_year

| resource_name	| plant	| period      |	bns_rtrmnt_d_oth     | bns_rtrmnt_a         | bns_rtrmnt_b         | bns_rtrmnt_c         |	consumable_tools | depr_common_unex   	| depr_unique_unex     | division_exp_depre   |	division_exp_labor   | division_exp_other  	| general_expense	 | interplant	| labor_a |  labor_b | labor_c | labor_d_others   | operating_supply |	r_m_forging_mold | repair_maintenance  	| tax_insurance   |	utilities | gpq_cc | key	             | sum_labor | sum_foh_fixed | sum_foh_Var | sum_unfinish_depre |	 sum_exclusive_depre  |
| ------------- | ----- | ----------- | -------------------- | -------------------- | -------------------- | -------------------- | -----------------| -------------------- | -------------------- | -------------------- | ---------------------| -------------------- | ---------------- | ---------- | ------- | ---------| ------- |----------------- | ---------------- | ----------------- | -------------------- | --------------- | --------- | ------ | ----------------- |--------- | -------------- | ----------- | ------------------ | --------------------- | 
| 111010C101	  | 4350	| 004.2025	  |                   62 |               61.428 |                   48 |                   66 |           34.895 |               30.393 |                    0 |                3.329 |              159.495 |               81.500 |           49.201 |     18.743	| 114.829 |   24.692 |  28.239 |           38.808 |           52.604 |                 0 |              65.668	|           6.046	|    30.630 | 30.007 | 111010C10104.2025 |  427.667 |	 202.415 	     | 136.872     |	        33.722    |                     - |
| 111010C101	  | 4350	| 005.2025	  |                  -13 |               47.834 |                  -14 |                  -27 |           24.374 |               23.947 |                    0 |                2.713 |              130.512 |               65.805 |           35.777 |     -7.969 |  95.681 |   26.568 |  18.376 |           48.936 |           35.583 |                 0 |              88.246	|           5.739	|    23.272 | 37.229 | 111010C10105.2025 |  367.853 |	 195.567 	     | 75.260 	   |          26.660    |                     - |
| 111010C101	  | 4350	| 006.2025	  |                    0 |               40.567 |                    0 |                    0 |           24.613 |               28.650 |                    0 |                3.054 |              140.318 |               94.569 |           63.011 |      5.890 | 105.877 |   23.494 |  25.569 |           34.737 |           36.316 |                 0 |             122.266	|           4.770 |    28.837 | 37.918 | 111010C10106.2025 |  370.562 |	 284.616 	     | 95.656 	   |          31.704    |                     - |
| 111010C101	  | 4350	| 007.2025	  |                    0 |                    0 |                    0 |                    0 |           19.486 |               24.758 |                    0 |                2.668 |              125.196 |               69.762 |           88.652 |      5.699 |  83.066 |   17.631 |  20.043 |           48.479 |           38.205 |                 0 |             141.940	|           3.975 |    27.326 | 41.439 | 111010C10107.2025 |  294.415 |	 304.329 	     | 90.716 	   |          27.426    |                     - |
| 111010C101	  | 4350	| 008.2025	  |                    0 |               75.014 |                    0 |                    0 |           27.847 |               30.482 |                    0 |                3.025 |              154.824 |               53.001 |           57.506 |      4.582 | 105.380 |   29.593 |  29.858 |           44.548 |           38.234 |                 0 |              77.811	|           5.240	|    24.943 | 50.638 | 111010C10108.2025 |  439.217 |	 193.558 	     | 95.606 	   |          33.507    |                     - |
| 111010C101	  | 4350	| 009.2025	  |                    0 |               44.176 |                    0 |                    0 |           18.831 |               22.322 |                    0 |                2.217 |              102.134 |               49.449 |           38.576 |     11.099 |  77.553 |   20.150 |  22.407 |           35.406 |           28.409 |                 0 |              60.712	|           5.233	|    22.865 | 39.695 | 111010C10109.2025 |  301.826 |	 153.970 	     | 81.204 	   |          24.539    |                     - |
| ------------- | ----- | ----------- | -------------------- | -------------------- | -------------------- | -------------------- | -----------------| -------------------- | -------------------- | -------------------- | ---------------------| -------------------- | ---------------- | ---------- | ------- | ---------| ------- |----------------- | ---------------- | ----------------- | -------------------- | --------------- | --------- | ------ | ----------------- |--------- | -------------- | ----------- | ------------------ | --------------------- | 
| 114010C060	  | 4350	| 004.2025	  |                   67 |               53.220 |               16.516 |                   71 |           64.699 |               59.325 |                  204 |                4.087 |              195.794 |              100.048 |           42.332 |     23.009 | 100.493 |   55.726 |  31.685 |           43.546 |           69.103 |                 0 |              89.629	|           7.818	|    37.182 | 13.756 | 114010C06004.2025 |  497.118 |	 239.827 	     | 193.993     |	        63.412    |                   204 |
| 114010C060	  | 4350	| 005.2025	  |                  -16 |               40.386 |               18.215 |                  -32 |           42.616 |               50.248 |                  173 |                3.448 |              165.867 |               83.631 |           37.713 |    -10.128 |  81.263 |   62.443 |  20.619 |           54.916 |           53.175 |                 0 |             105.764	|           8.460	|    31.640 | 16.213 | 114010C06005.2025 |  443.661 |	 235.568 	     | 117.303     |	        53.696    |                   173 |
| 114010C060	  | 4350	| 006.2025	  |                    0 |               30.142 |                9.693 |                    0 |           34.378 |               51.055 |                  163 |                3.201 |              147.049 |               99.106 |           44.298 |      6.172 |  83.031 |   50.358 |  28.694 |           38.983 |           36.388 |                 0 |             150.140	|           5.512	|    29.689 | 17.206 | 114010C06006.2025 |  387.950 |	 299.056 	     | 106.627     |	        54.256    |                   163 |
| 114010C060	  | 4350	| 007.2025	  |                    0 |                    0 |                    0 |                    0 |           36.669 |               45.909 |                  145 |                3.000 |              140.785 |               78.449 |           87.332 |      6.408 |  67.671 |   37.981 |  22.493 |           54.405 |           44.342 |                 0 |             166.980	|           4.748	|    31.655 | 19.377 | 114010C06007.2025 |  323.335 |	 337.509 	     | 119.074     |	        48.909    |                   145 |
| 114010C060	  | 4350	| 008.2025	  |                    0 |               63.871 |               17.916 |                    0 |           49.914 |               62.026 |                  195 |                4.086 |              209.077 |               71.574 |           60.135 |      6.187 |  95.148 |   57.132 |  33.508 |           49.994 |           50.512 |                 0 |             154.608	|           6.560	|    31.743 | 14.392 | 114010C06008.2025 |  526.646 |	 292.877 	     | 138.356     |	        66.112    |                   195 |
| 114010C060	  | 4350	| 009.2025	  |                    0 |               44.316 |               11.541 |                    0 |           43.159 |               48.381 |                  152 |                3.191 |              146.980 |               71.163 |           44.937 |     15.972 |  71.219 |   39.183 |  25.146 |           39.734 |           39.867 |                 0 |             115.357	|           7.302	|    30.071 | 18.478 | 114010C06009.2025 |  378.119 |	 238.759 	     | 129.069     |          51.572    |                   152 |                                                                             
| ------------- | ----- | ----------- | -------------------- | -------------------- | -------------------- | -------------------- | -----------------| -------------------- | -------------------- | -------------------- | ---------------------| -------------------- | ---------------- | ---------- | ------- | ---------| ------- |----------------- | ---------------- | ----------------- | -------------------- | --------------- | --------- | ------ | ----------------- |--------- | -------------- | ----------- | ------------------ | --------------------- |                                                                                                          


COST ITEM PER PART 
source : Cost Item Per Period file, to obtain the value 
          1. Each cost item children summarized for each cost item 
          2. Summarized for each part and each month for the period of 6 months (depend on the reporting start and end)
          3. divided by sum of GPQ for 6 month
          4. We got the value


| ------------- | ----- | ----------- | -------------------- | --------- | ------------ | -------------------- | -----------------| -------------------- |
| Resource Name	| Plant	| period      |        gpq_cc        | labor     |  FOH Fixed	  |  FOH Var 	           | Unfinish Depre. 	| Exclusive Depre.     |
| ------------- | ----- | ----------- | -------------------- | --------- | ------------ | -------------------- | -----------------| -------------------- |
| 111010C101	  | 4350	| 004.2025	  |       236.926        | 2.201.540 |	 1.334.455 	|              575.314 | 177.558          |                      | 
| 114010C060	  | 4350	| 004.2025	  |        99.422        | 2.556.829 |   1.643.596 	|              804.422 	| 337.957         |                1.032 | 
| ------------- | ----- | ----------- | -------------------- | --------- | ------------ | -------------------- | -----------------| -------------------- |


---
TB_T_PROCESS_COST
### PROCESS COST (Source Data Table)
File : Process Cost Template
Sheet : Default

| period      | Plant | MaterialNumber | Header       | MainCostComponentName | Quantity |
| ----------- | ----- | -------------- | ------       | --------------------- | -------- |
| 04.2025     | 4350  | 51401-KWW-641  | Raw Material | Raw Material          | 3083.00  |
| 04.2025     | 4350  | 51401-KWW-641  | Tooling      | Tooling Outhouse      | 3363.00  |
| 04.2025     | 4350  | 51401-KWW-641  | Labor        | Labor A               | 2965.00  |
| 04.2025     | 4350  | 51401-KWW-641  | FOH Fixed    | General Expense       | 1545.50  |
| 04.2025     | 4350  | 51401-KWW-641  | FOH Fixed    | Tax & Insurance       | 773.50   |
| 04.2025     | 4350  | 51401-KWW-641  | FOH Fixed    | Repair & Maintenance  | 773.00   |
| 04.2025     | 4350  | 51401-KWW-641  | FOH Variable | Operating Supply      | 1585.00  |
| 04.2025     | 4350  | 51401-KWW-641  | FOH Variable | Consumable Tools      | 1585.00  |
| 04.2025     | 4350  | 51401-KWW-641  | Depreciation | Depre. Common         | 3358.00  |
| 04.2025     | 4350  | 51401-KWW-641  | Depreciation | Depre. Exclusive      | 504.00   |
|----------------------------------------------------------------------------------------|
| 04.2025     | 4350  | 51402-KWW-640  | Raw Material | Raw Material          | 3113.00  |
| 04.2025     | 4350  | 51402-KWW-640  | Tooling      | Tooling Outhouse      | 3393.00  |
| 04.2025     | 4350  | 51402-KWW-640  | Labor        | Labor A               | 2995.00  |
| 04.2025     | 4350  | 51402-KWW-640  | FOH Fixed    | General Expense       | 1560.50  |
| 04.2025     | 4350  | 51402-KWW-640  | FOH Fixed    | Tax & Insurance       | 780.25   |
| 04.2025     | 4350  | 51402-KWW-640  | FOH Fixed    | Repair & Maintenance  | 780.25   |
| 04.2025     | 4350  | 51402-KWW-640  | FOH Variable | Operating Supply      | 1600.00  |
| 04.2025     | 4350  | 51402-KWW-640  | FOH Variable | Consumable Tools      | 1600.00  |
| 04.2025     | 4350  | 51402-KWW-640  | Depreciation | Depre. Common         | 3388.00  |
| 04.2025     | 4350  | 51402-KWW-640  | Depreciation | Depre. Exclusive      | 508.00   |
|----------------------------------------------------------------------------------------|
| 04.2025     | 4350  | 51402-KWW-641  | Raw Material | Raw Material          | 2828.00  |
| 04.2025     | 4350  | 51402-KWW-641  | Tooling      | Tooling Outhouse      | 2703.00  |
| 04.2025     | 4350  | 51402-KWW-641  | Labor        | Labor A               | 3090.00  |
| 04.2025     | 4350  | 51402-KWW-643  | Raw Material | Raw Material          | 2669.00  |
| 04.2025     | 4350  | 51402-KWW-643  | Tooling      | Tooling Outhouse      | 2811.00  |
| 04.2025     | 4350  | 51402-KWW-643  | Labor        | Labor A               | 3058.00  |




===================
  REPORTS
-------------------

---
### MATERIAL COST REPORT
| EG Model | Category |  Casting Part  |    CC   | Material No  |              Material Name                | Material Category |   Price 	| Gentani |	    Total   |
| -------- | -------- | -------------- | --------|--------------|-------------------------------------------|------------------ |---------- | ------- | ----------- |
| NR       |	HEV	    | Block Cylinder | AZC100  | B895-010517  | ANTIMON SB 99.0 % MAX (EX. JAPAN YUSHIN )	| Additive          |	328.333,0	|     0,0	|     4.790,0 |
| NR       |	HEV	    | Block Cylinder | AZC100  | B895-022001  | CARBON LOW NITROGEN	                      | Additive          |  19.500,0 |     0,7 |    12.843,0 |
| NR       |	HEV	    | Block Cylinder | AZC100  | B895-061517  | FERRO SILICON 0.75 (EXFESIL) YUSHIN	      | Additive          |	 28.000,0 |	    0,8	|    21.974,0 |
| NR       |	HEV	    | Block Cylinder | AZC100  | B895-061519  | FERRO MANGAN for FCD Cams(13%)            |                   |  22.000,0 |         |             |
| NR       |	HEV	    | Block Cylinder | AZC100  | B895-080556  | CARBON G-HIGH JG-01                       |                   |  18.160,0 |         |             |
| NR       |	HEV	    | Camshaft 1	   | AZC100  | B895-010519  | ANTIMON METAL                             |                   |           |         |             |
| NR       |	HEV	    | Camshaft 1	   | AZC100  | B895-031561  | CARBURIZER CARBON RISER HCM-A(CPC-A)OCTO  |                   |           |         |             |
| NR       |	HEV	    | Camshaft 1	   | AZC100  | B895-061519  | FERRO MANGAN for FC (87%)                 |                   |           |         |             |
| NR       |	HEV	    | Camshaft 1	   | AZC100  | B895-062518  | Ferro Silicon Low Al Kinsei Matex Cam's	  | Additive          |  29.567,0 |	    0,1 |     1.687,0 |
| NR       |	HEV	    | Camshaft 1	   | AZC100  | B895-090720  | Inoculant Ultraseed LG size 0,7-2mm       |                   |           |         |             |
| NR       |	HEV	    | Camshaft 2	   | AZC100  | B895-010518  | ANTIMON (SB) SHOT S 3-8 MM KINSEI MATEC   |                   |           |         |             |
| NR       |	HEV	    | Camshaft 2	   | AZC100  | B895-031560  | CARBON DTCA-09 DURATIGHT / OCTO           |                   |           |         |             |
| NR       |	HEV	    | Camshaft 2	   | AZC100  | B895-031561  | CARBURIZER CARBON RISER HCM-A(CPC-A)OCTO  |                   |           |         |             |
| NR       |	HEV	    | Camshaft 2	   | AZC100  | B895-033558  | RECARBURIZER DG-LNS MARUTOYO              | Additive          | 10.900,0	|     0,0	|       109,0	|
| NR       |	HEV	    | Camshaft 2	   | AZC100  | B895-061517  | FERRO SILICON 0.75 (EXFESIL) YUSHIN       |                   |           |         |             |




---
### MATERIAL MASTER

| ID | EG Model | Category |  Casting Part  |    CC   | Material No  |              Material Name                | Material Category |
|    | -------- | -------- | -------------- | --------|--------------|-------------------------------------------|------------------ |
|    | NR       |	HEV	     | Block Cylinder | AZC100  | B895-010517  | ANTIMON SB 99.0 % MAX (EX. JAPAN YUSHIN ) | Additive          |
|    | NR       |	HEV	     | Block Cylinder | AZC100  | B895-022001  | CARBON LOW NITROGEN	                     | Additive          |
|    | NR       |	HEV	     | Block Cylinder | AZC100  | B895-061517  | FERRO SILICON 0.75 (EXFESIL) YUSHIN	     | Additive          |
|    | NR       |	HEV	     | Block Cylinder | AZC100  | B895-061519  | FERRO MANGAN for FCD Cams(13%)            |                   |
|    | NR       |	HEV	     | Block Cylinder | AZC100  | B895-080556  | CARBON G-HIGH JG-01                       |                   |
|    | NR       |	HEV	     | Camshaft 1	    | AZC100  | B895-010519  | ANTIMON METAL                             |                   |
|    | NR       |	HEV	     | Camshaft 1	    | AZC100  | B895-031561  | CARBURIZER CARBON RISER HCM-A(CPC-A)OCTO  |                   |
|    | NR       |	HEV	     | Camshaft 1	    | AZC100  | B895-061519  | FERRO MANGAN for FC (87%)                 |                   |
|    | NR       |	HEV	     | Camshaft 1	    | AZC100  | B895-062518  | Ferro Silicon Low Al Kinsei Matex Cam's	 | Additive          |
|    | NR       |	HEV	     | Camshaft 1	    | AZC100  | B895-090720  | Inoculant Ultraseed LG size 0,7-2mm       |                   |
|    | NR       |	HEV	     | Camshaft 2	    | AZC100  | B895-010518  | ANTIMON (SB) SHOT S 3-8 MM KINSEI MATEC   |                   |
|    | NR       |	HEV	     | Camshaft 2	    | AZC100  | B895-031560  | CARBON DTCA-09 DURATIGHT / OCTO           |                   |
|    | NR       |	HEV	     | Camshaft 2	    | AZC100  | B895-031561  | CARBURIZER CARBON RISER HCM-A(CPC-A)OCTO  |                   |
|    | NR       |	HEV	     | Camshaft 2	    | AZC100  | B895-033558  | RECARBURIZER DG-LNS MARUTOYO              | Additive          |
|    | NR       |	HEV	     | Camshaft 2	    | AZC100  | B895-061517  | FERRO SILICON 0.75 (EXFESIL) YUSHIN       |                   |


============
  THRASH
------------

---
### PPR DATA

|  part_no (FK) | period/scenario | std_cost | foh_var | foh_fixed | tooling_oh | raw_material | labor | depre_common | depre_exclusive | mh_cost | total_cost | sales_volume | prod_volume |
| ------------- | --------------- | -------- | ------- | --------- | ---------- | ------------ | ----- | ------------ | --------------- | ------- | ---------- | ------------ | ----------- |
| 51401-KWW-641	| 2024-08	        | 9300	   | 3170	   | 3091	     | 3363	      | 3083	2965	3358	504	297	19161	0	0
| 51401-KWW-641	| 2025-02	        | 9533	   | 3249	   | 3168	     | 3447	      | 3160	3039	3442	516	304	19639	0	0
| 51401-KWW-641	| pbmd_values	9221	3148	3070	3340	3062	2945	3335	501	295	18981	0	0
| 51401-KWW-641	| inflation	9233	3152	3074	3344	3066	2949	3339	501	295	19004	0	0
| 51402-KWW-640	| 2024-08	9400	3200	3121	3393	3113	2995	3388	508	299	19269	0	0
| 51402-KWW-640	| 2025-02	9633	3279	3198	3477	3190	3069	3472	521	307	19739	0	0
| 51402-KWW-640	| pbmd_values	9321	3178	3100	3370	3092	2975	3365	505	297	19141	0	0
| 51402-KWW-640	| inflation	9333	3182	3104	3374	3096	2979	3369	506	298	19164	0	0
| 51402-KWW-641	| 2024-08	8600	3000	2929	2703	2828	3090	2997	450	309	17547	0	0
| 51402-KWW-641	| 2025-02	8816	3075	3005	2770	2900	3170	3073	461	317	17987	0	0
| 51402-KWW-641	| pbmd_values	8732	2951	3180	2660	2731	3102	2850	428	310	17474	0	0
| 51402-KWW-641	| inflation	8669	2934	3165	2651	2726	3100	2852	429	311	17553	0	0
| 51402-KWW-643	| 2024-08	8900	3020	3169	2811	2669	3058	3149	472	306	17876	0	0
| 51402-KWW-643	| 2025-02	9621	3259	3422	3037	2881	3304	3401	509	306	19240	0	0
| 51402-KWW-643	| pbmd_values	9011	3111	3030	2965	2999	2831	3011	452	283	17947	0	0
| 51402-KWW-643	| inflation	8949	3094	3017	2956	2994	2830	3014	453	284	18033	0	0


---
### PPR CALCULATION

| part_no (FK)  | column_name            | group_name  | tooling_oh | raw_material | TOTAL_purchase_cost | labor | foh_fix  | foh_var | depre_common | depre_exclusive | TOTAL_process_cost | manhour | sales_volume | prod_volume |
| ------------- | ----------             | calculation | ---------- | ------------ | ------------------- | ----- | -------- | ------- | ------------ | --------------- | ------------------ | ------- | ------------ | ----------- |
| 51401-KWW-641 | 2024-08                | calculation | 3363       | 3083         | 9300                | 2965  | 3091     | 3170    | 3358         | 504             | 297                | 19161   | 0            | 0           |
| 51401-KWW-641 | 2025-02                | calculation | 3363       | 3083         | 9300                | 2965  | 3091     | 3170    | 3358         | 504             | 297                | 19161   | 0            | 0           |
| 51402-KWW-643 | 2024-08                | calculation | 2811       | 2669         | 8900                | 2830  | 3169     | 3020    | 472          | 306             | 17876              | 0       | 0            | 0           |
|               | volume                 | analysis    |
|               | inflation              | analysis    |
|               | CR                     | analysis    |
|               | Material Price Impact  | analysis    |
|               | Gentan-i Impact        | analysis    |
|               | Others                 | analysis    |


****************
PBMD IHP TABLE
****************
Table TB_R_INHOUSE_COST_EG {
  √ PART_NO varchar(12) [pk]
  PARENT_PART_NO varchar(12) [pk]
  PPR_PERIOD varchar(6) [pk]
  FOB_CALCULATION_ID varchar(20)
  COST_MOVEMENT_ID varchar(20)
  √ ENGINE_TYPE varchar(10) [not null]
  √ PROCESS_LABOR_COST float [not null]
  √ PROCESS_LABOR_COST_FINAL float [not null]
  √ PROCESS_FOH_FIXED_COST float [not null]
  √ PROCESS_FOH_FIXED_COST_FINAL float [not null]
  √ PROCESS_FOH_VAR_COST float [not null]
  √ PROCESS_FOH_VAR_COST_FINAL float [not null]
  √ PROCESS_UNFINISHED_DEPRE_COST float [not null]
  √ PROCESS_UNFINISHED_DEPRE_COST_FINAL float [not null]
  √ PROCESS_EXCLUSIVE_DEPRE_COST float [not null]
  √ PROCESS_EXCLUSIVE_DEPRE_COST_FINAL float [not null]
  √ PROCESS_TOTAL_PROCESS_COST float [not null]
  √ PROCESS_TOTAL_PROCESS_COST_FINAL float [not null]
  √ INHOUSE_MATERIAL_RAW_MATERIAL float [not null]
  √ INHOUSE_MATERIAL_RAW_MATERIAL_FINAL float [not null]
  INHOUSE_MATERIAL_TOOLING_OUTHOUSE_COST float [not null]
  INHOUSE_MATERIAL_TOOLING_OUTHOUSE_COST_FINAL float [not null]
  TOTAL_INHOUSE_COST float [not null]
  TOTAL_INHOUSE_COST_FINAL float [not null]
  REMARK varchar(200)
  SYSTEM_SRC varchar(25) 
  CREATED_DT datetime [not null]
  CREATED_BY varchar(50) [not null]
  CHANGED_DT datetime [not null]
  CHANGED_BY datetime [not null]
  FILE_ID varchar(50) [ref: > TB_R_FILE.FILE_ID, not null]
}


----
### PPR Columns

| col_id | column_name | group_name |
| ------ | ----------- | ---------- |
| 1       | volume                 | analysis    |
| 2       | inflation              | analysis    |
| 3       | CR                     | analysis    |
| 4       | Material Price Impact  | analysis    |
| 5       | Gentan-i Impact        | analysis    |
| 6       | Others                 | analysis    |


---
### PPR ANALYSIS
| part_no (FK)  | header_name           | tooling_oh | raw_material | TOTAL_purchase_cost | labor | foh_fix  | foh_var | depre_common | depre_exclusive | TOTAL_process_cost | manhour | sales_volume | prod_volume |
| ------------- | --------------------- | ---------- | ------------ | ------------------- | ----- | -------- | ------- | ------------ |
| 51401-KWW-641 | volume                |
| 51401-KWW-641 | inflation             |
| 51401-KWW-641 | CR                    |
| 51401-KWW-641 | Material Price Impact |
| 51401-KWW-641 | Gentan-i Impact       |
| 51401-KWW-641 | Others                |


---
### PROCESS COST SUMMARY (Source Data Table)
Note:
Quantity already summarized from the PROCESS COST table

| Period/Year | MaterialNumber | header       |  Quantity |
| ----------- | -------------- | ------------ |  -------- |
| 04.2025     | 51401-KWW-641  | Labor        |  3083.00  |
| 04.2025     | 51401-KWW-641  | FOH Fixed    |  3363.00  |
| 04.2025     | 51401-KWW-641  | FOH Variable |  2965.00  |
| 04.2025     | 51401-KWW-641  | Depreciation |  1545.50  |
| 04.2025     | 51401-KWW-641  | Raw Material |  773.50   |
| 04.2025     | 51401-KWW-641  | Tooling      |  773.00   |

| 04.2025     | 51402-KWW-640  | Labor        |  3393.00  |
| 04.2025     | 51402-KWW-640  | FOH Fixed    |  2995.00  |
| 04.2025     | 51402-KWW-640  | FOH Variable |  1560.50  |
| 04.2025     | 51402-KWW-640  | Depreciation |  780.25   |
| 04.2025     | 51402-KWW-640  | Raw Material |  780.25   |
| 04.2025     | 51402-KWW-640  | Tooling      |  1600.00  |

| 04.2025     | 51402-KWW-643  | Labor        | 2828.00   |
| 04.2025     | 51402-KWW-643  | FOH Fixed    | 2703.00   |
| 04.2025     | 51402-KWW-643  | FOH Variable | 3090.00   |
| 04.2025     | 51402-KWW-643  | Depreciation | 2669.00   |     
| 04.2025     | 51402-KWW-643  | Raw Material | 2811.00   |
| 04.2025     | 51402-KWW-643  | Tooling      | 3058.00   |


---
### ENGINE_TYPE
Note: NOT USED

| EG_TYPE/Category | Description |
| ---------------- | ------------------------- |
| HEV              | Hybrid Electric Vehicle   | 
| ICE              | Internal Combustion Engine| 
| BEV              | Battery EV                |  
| PHEV             | Plug-in Hybrid EV         |  
| FCEV             | Fuel Cell EV              | 
| FFHV             | Flex-Fuel Hybrid Engines  |  
| NG-ICE           | Next Generation ICE       | 


---
### EG_MODEL
Note: NOT USED

| model_code |  eg_type  |
| ---------- | --------- |
|  NR        | ICE       |
|  TR        | ICE       |
|  1TR       | ICE       |
|  2TR       | ICE       |


























































































































































